# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'ReviewItYourself' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for How-To
pod 'lottie-ios'
pod 'SDWebImage'
pod 'GoogleSignIn'
pod "YoutubePlayer-in-WKWebView", "~> 0.3.0"
end
